apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  labels:
    app: notification
spec:
  replicas: 3
  selector:
    matchLabels:
      app: notification
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: doctor-appointment-notification-v2
          image: doctor-appointment-notification:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80